$dll32_path = ".\hotfix\nt\libPortability.dll"
$dll64_path = ".\hotfix\nt64\libPortability.dll"

Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\ISE\sysgen\bin\nt64\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\ISE\sysgen\bin\nt64\libPortability.dll.orig"
Copy-Item -Path $dll64_path -Destination "C:\Xilinx\14.7\ISE_DS\ISE\sysgen\bin\nt64\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\ISE\sysgen\bin\nt\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\ISE\sysgen\bin\nt\libPortability.dll.orig"
Copy-Item -Path $dll32_path -Destination "C:\Xilinx\14.7\ISE_DS\ISE\sysgen\bin\nt\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt64\sdk\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt64\sdk\libPortability.dll.orig"
Copy-Item -Path $dll64_path -Destination "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt64\sdk\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt64\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt64\libPortability.dll.orig"
Copy-Item -Path $dll64_path -Destination "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt64\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt\libPortability.dll.orig"
Copy-Item -Path $dll32_path -Destination "C:\Xilinx\14.7\ISE_DS\EDK\lib\nt\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\.xinstall\bin\nt64\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\.xinstall\bin\nt64\libPortability.dll.orig"
Copy-Item -Path $dll64_path -Destination "C:\Xilinx\14.7\ISE_DS\.xinstall\bin\nt64\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\.xinstall\bin\nt\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\.xinstall\bin\nt\libPortability.dll.orig"
Copy-Item -Path $dll32_path -Destination "C:\Xilinx\14.7\ISE_DS\.xinstall\bin\nt\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\common\lib\nt64\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\common\lib\nt64\libPortability.dll.orig"
Copy-Item -Path $dll64_path -Destination "C:\Xilinx\14.7\ISE_DS\common\lib\nt64\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\common\lib\nt\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\common\lib\nt\libPortability.dll.orig"
Copy-Item -Path $dll32_path -Destination "C:\Xilinx\14.7\ISE_DS\common\lib\nt\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\ISE\lib\nt64\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\ISE\lib\nt64\libPortability.dll.orig"
Copy-Item -Path $dll64_path -Destination "C:\Xilinx\14.7\ISE_DS\ISE\lib\nt64\libPortability.dll"
Copy-Item -Path "C:\Xilinx\14.7\ISE_DS\ISE\lib\nt\libPortability.dll" -Destination "C:\Xilinx\14.7\ISE_DS\ISE\lib\nt\libPortability.dll.orig"
Copy-Item -Path $dll32_path -Destination "C:\Xilinx\14.7\ISE_DS\ISE\lib\nt\libPortability.dll"
[Environment]::SetEnvironmentVariable('XILINX_VC_CHECK_NOOP', '1', 'User')